name: polyticks
description: A political social media platform for civic engagement.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.2.1
  cached_network_image: ^3.3.1
  timeago: ^3.6.1
  flutter_animate: ^4.5.0
  image_picker: ^1.1.2
  supabase_flutter: ^2.17.1
  flutter_image_compress: ^2.5.1
  http: ^1.2.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.0.0
  logger: ^2.0.0
  share_plus: ^13.3.0
  flutter_radio_group: ^2.1.0
  url_launcher: ^6.3.2
  app_links: ^7.2.1
  razorpay_flutter: ^1.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.0
  share_plus_platform_interface: ^7.2.0
  build_runner: ^2.5.4
  riverpod_generator: ^2.2.5
  shared_preferences: ^2.5.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
