allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

// Redirect build directory to avoid conflicts with Flutter's build system
gradle.buildFinished {
    rootProject.buildDir = file("../../build")
}

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}