// Deep-link / Open Graph handling for /post/:id routes.
//
// V3 Phase 5 — T5.2: when the web app is served at /post/:id, the document
// <head> must expose <meta property="og:image"> pointing at the dynamic
// share-card PNG generated by the `generate-share-card` Edge Function.
// The function keys objects deterministically as preview_<post_id>.png in the
// PUBLIC `share_previews` bucket (upsert overwrite), so the URL is resolvable
// without invoking the function.
//
// LIMITATION (documented per pending/V3_PHASE3_TESTING.md T5.2): crawlers such
// as WhatsApp/X do NOT execute JS. This client-side injection makes og:image
// correct for JS-aware consumers and same-page previews; full crawler unfurl
// additionally requires serving prerendered head tags for /post/:id (e.g. an
// SSR/prerender layer or an HTML-rendering edge rewrite). Tracked for v4.

const SUPABASE_URL = 'https://sbdwwmbocyqlkztptskb.supabase.co';

/** Returns the post UUID if [pathname] is a /post/:id deep link, else null. */
export function parsePostDeepLink(pathname: string): string | null {
  const match = pathname.match(/^\/post\/([0-9a-fA-F-]{36})\/?$/);
  return match ? match[1] : null;
}

/** Dynamic share-card PNG URL for a post (public bucket, deterministic key). */
export function shareCardUrl(postId: string): string {
  return `${SUPABASE_URL}/storage/v1/object/public/share_previews/preview_${postId}.png`;
}

function setMeta(property: string, content: string): void {
  let el = document.head.querySelector<HTMLMetaElement>(
    `meta[property="${property}"]`,
  );
  if (!el) {
    el = document.createElement('meta');
    el.setAttribute('property', property);
    document.head.appendChild(el);
  }
  el.setAttribute('content', content);
}

/** Injects/updates the Open Graph tags for a post deep link. */
export function applyPostOgMeta(postId: string): void {
  setMeta('og:title', 'Poll on Polyticks');
  setMeta('og:description', 'Check out this local poll on Polyticks.');
  setMeta('og:image', shareCardUrl(postId));
  setMeta('og:url', `${window.location.origin}/post/${postId}`);
  setMeta('og:type', 'article');
}

/** Entry point: applies OG metas when the current path is a post deep link. */
export function handleDeepLinkOnLoad(): void {
  const postId = parsePostDeepLink(window.location.pathname);
  if (postId) applyPostOgMeta(postId);
}
